---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cron-scheduler-configmap-ds
  namespace: openshift-multus
spec:
  selector:
    matchLabels:
      app: cron-scheduler-configmap-ds
  template:
    metadata:
      labels:
        app: cron-scheduler-configmap-ds
    spec:
      containers:
        - name: cron-scheduler-configmap-pod
          image:  {{.MultusImage}}
          command: ["/bin/bash", "-c"]
          env:
            # Define environment variables
            - name: CRON_SCHEDULE
              valueFrom:
                configMapKeyRef: 
                  name: cron-scheduler-configmap
                  key: cron_schedule
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command: ["/bin/bash", "-c", "test -f /ready/ready"]
            initialDelaySeconds: 1
          volumeMounts:
            - mountPath: /entrypoint
              name: cron-scheduler-configmap
            - mountPath: /host/etc/cni/tuning/
              name: tuning-conf-dir
              readOnly: false
            - mountPath: /ready
              name: ready
              readOnly: false
      volumes:
        - name: cron-scheduler-configmap
          configMap:
            name: cron-scheduler-configmap
            namespace: openshift-multus
            items: 
            - key: "cron_schedule"
              path: "cron_schedule"
          defaultMode: 0744
        - hostPath:
            path: /etc/cni/tuning/
            type: DirectoryOrCreate
          name: tuning-conf-dir
        - name: ready
          emptyDir: { }