// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalNetworkDefinition) DeepCopyInto(out *AdditionalNetworkDefinition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalNetworkDefinition.
func (in *AdditionalNetworkDefinition) DeepCopy() *AdditionalNetworkDefinition {
	if in == nil {
		return nil
	}
	out := new(AdditionalNetworkDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetwork) DeepCopyInto(out *ClusterNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetwork.
func (in *ClusterNetwork) DeepCopy() *ClusterNetwork {
	if in == nil {
		return nil
	}
	out := new(ClusterNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultNetworkDefinition) DeepCopyInto(out *DefaultNetworkDefinition) {
	*out = *in
	if in.OpenshiftSDNConfig != nil {
		in, out := &in.OpenshiftSDNConfig, &out.OpenshiftSDNConfig
		*out = new(OpenshiftSDNConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OVNKubernetesConfig != nil {
		in, out := &in.OVNKubernetesConfig, &out.OVNKubernetesConfig
		*out = new(OVNKubernetesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtherConfig != nil {
		in, out := &in.OtherConfig, &out.OtherConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultNetworkDefinition.
func (in *DefaultNetworkDefinition) DeepCopy() *DefaultNetworkDefinition {
	if in == nil {
		return nil
	}
	out := new(DefaultNetworkDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigSpec) DeepCopyInto(out *NetworkConfigSpec) {
	*out = *in
	if in.ClusterNetworks != nil {
		in, out := &in.ClusterNetworks, &out.ClusterNetworks
		*out = make([]ClusterNetwork, len(*in))
		copy(*out, *in)
	}
	in.DefaultNetwork.DeepCopyInto(&out.DefaultNetwork)
	if in.AdditionalNetworks != nil {
		in, out := &in.AdditionalNetworks, &out.AdditionalNetworks
		*out = make([]AdditionalNetworkDefinition, len(*in))
		copy(*out, *in)
	}
	if in.DeployKubeProxy != nil {
		in, out := &in.DeployKubeProxy, &out.DeployKubeProxy
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigSpec.
func (in *NetworkConfigSpec) DeepCopy() *NetworkConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigStatus) DeepCopyInto(out *NetworkConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigStatus.
func (in *NetworkConfigStatus) DeepCopy() *NetworkConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNKubernetesConfig) DeepCopyInto(out *OVNKubernetesConfig) {
	*out = *in
	if in.GenevePort != nil {
		in, out := &in.GenevePort, &out.GenevePort
		*out = new(uint32)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(uint32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNKubernetesConfig.
func (in *OVNKubernetesConfig) DeepCopy() *OVNKubernetesConfig {
	if in == nil {
		return nil
	}
	out := new(OVNKubernetesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftSDNConfig) DeepCopyInto(out *OpenshiftSDNConfig) {
	*out = *in
	if in.VXLANPort != nil {
		in, out := &in.VXLANPort, &out.VXLANPort
		*out = new(uint32)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(uint32)
		**out = **in
	}
	if in.UseExternalOpenvswitch != nil {
		in, out := &in.UseExternalOpenvswitch, &out.UseExternalOpenvswitch
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftSDNConfig.
func (in *OpenshiftSDNConfig) DeepCopy() *OpenshiftSDNConfig {
	if in == nil {
		return nil
	}
	out := new(OpenshiftSDNConfig)
	in.DeepCopyInto(out)
	return out
}
