---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-router-cni-deployment
  namespace: "{{.EgressRouterNamespace}}"
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
  labels:
    app: egress-router-cni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egress-router-cni
  template:
    metadata:
      labels:
        app: egress-router-cni
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name":"egress-router-cni-nad",
              "default-route": ["{{.Gateway}}"]
            }
          ]
    spec:
      containers:
        - name: egress-router-cni-pod
          image: "{{.EgressRouterPodImage}}"
          command: ['/bin/sh', '-c', 'sleep infinity']
          terminationMessagePolicy: FallbackToLogsOnError
