---
# service to expose the ovn-master pod
# at present ovn-master is limited to a single instance so
# when the cluster has multiple masters we can get to the
# ovn-master via this service.
apiVersion: v1
kind: Service
metadata:
  name: ovnkube-master-external
  namespace: {{.HostedClusterNamespace}}
  annotations:
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
  labels:
    app: ovnkube-master
spec:
  selector:
    app: ovnkube-master
  ports:
  - name: north
    port: {{.OVN_NB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_NB_PORT}}
  - name: south
    port: {{.OVN_SB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_SB_PORT}}
{{ if .OVN_SB_NODE_PORT }}
    nodePort: {{.OVN_SB_NODE_PORT}}
{{ end }}
{{ if ne .OVNDbServiceType "NodePort" }}
  clusterIP: None
{{ end }}
  sessionAffinity: None
  type: {{.OVNDbServiceType}}

---
apiVersion: v1
kind: Service
metadata:
  name: ovnkube-master-internal
  namespace: {{.HostedClusterNamespace}}
  annotations:
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
    service.beta.openshift.io/serving-cert-secret-name: ovn-master-metrics-cert
  labels:
    app: ovnkube-master
spec:
  selector:
    app: ovnkube-master
  publishNotReadyAddresses: true
  ports:
  - name: north
    port: {{.OVN_NB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_NB_PORT}}
  - name: south
    port: {{.OVN_SB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_SB_PORT}}
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP
