{{ if eq .OVNDbServiceType "ClusterIP" }}
# There are two service types supported for ovn sb db in hypershift: ClusterIP and NodePort
# When ClusterIP is used we expose the service through the following route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ovnkube-sbdb
  namespace: {{.HostedClusterNamespace}}
  annotations:
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
  {{ if .OVNSbDbRouteLabels }}
  labels:
  {{ range $key, $value := .OVNSbDbRouteLabels }}
    "{{$key}}": "{{$value}}"
  {{ end }}{{ end  }}
spec:
  port:
    targetPort: {{.OVN_SB_PORT}}
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: ovnkube-master-external
  {{ if .OVNSbDbRouteHost }}
  host: {{.OVNSbDbRouteHost}}
  {{ end }}
{{ end }}
