---
# ovnkube-sbdb route exposed in extra cluster
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ovnkube-sbdb
  namespace: {{.HostedClusterNamespace}}
  clusterName: {{.ManagementClusterName}}
spec:
  port:
    targetPort: {{.OVN_SB_PORT}}
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: ovnkube-master
