---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ovnkube-master
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: monitor-ovn-master-metrics
  namespace: {{.HostedClusterNamespace}}
  clusterName: {{.ManagementClusterName}}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: https
    bearerTokenSecret:
      key: ""
    tlsConfig:
      ca:
        configMap:
          key: service-ca.crt
          name: openshift-service-ca.crt
      cert:
        secret:
          key: tls.crt
          name: ovn-master-metrics-cert
      keySecret:
        key: tls.key
        name: ovn-master-metrics-cert
      serverName: ovn-kubernetes-master.{{.HostedClusterNamespace}}.svc
    metricRelabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
    relabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{.HostedClusterNamespace}}
  selector:
    matchLabels:
      app: ovnkube-master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovnkube-master
  name: ovn-kubernetes-master
  namespace: {{.HostedClusterNamespace}}
  clusterName: {{.ManagementClusterName}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ovn-master-metrics-cert
spec:
  selector:
    app: ovnkube-master
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  sessionAffinity: None
  type: ClusterIP
