---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ovnkube-master
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: monitor-ovn-master-metrics
  namespace: {{.HostedClusterNamespace}}
  clusterName: {{.ManagementClusterName}}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
    path: /metrics
    metricRelabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
    relabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{.HostedClusterNamespace}}
  selector:
    matchLabels:
      app: ovnkube-master
