---
{{- if eq .RHOBSMonitoring "1" }}
apiVersion: monitoring.rhobs/v1
{{- else }}
apiVersion: monitoring.coreos.com/v1
{{- end }}
kind: ServiceMonitor
metadata:
  labels:
    app: ovnkube-control-plane
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
  name: monitor-ovn-control-plane-metrics
  namespace: {{.HostedClusterNamespace}}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: https
    bearerTokenSecret:
      key: ""
    tlsConfig:
      ca:
        configMap:
          key: {{.CAConfigMapKey}}
          name: {{.CAConfigMap}}
      cert:
        secret:
          key: tls.crt
          name: ovn-control-plane-metrics-cert
      keySecret:
        key: tls.key
        name: ovn-control-plane-metrics-cert
      serverName: ovn-kubernetes-control-plane.{{.HostedClusterNamespace}}.svc
    metricRelabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
    relabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{.HostedClusterNamespace}}
  selector:
    matchLabels:
      app: ovnkube-control-plane
---
apiVersion: v1
kind: Service
metadata:
  name: ovn-kubernetes-control-plane
  namespace: {{.HostedClusterNamespace}}
  annotations:
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
    service.beta.openshift.io/serving-cert-secret-name: ovn-control-plane-metrics-cert
  labels:
    app: ovnkube-control-plane
spec:
  selector:
    app: ovnkube-control-plane
  publishNotReadyAddresses: true
  ports:
    - name: metrics
      port: 9108
      protocol: TCP
      targetPort: 9108
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP
