apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: default
spec:
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo dummy-dep-1; sleep 10; done"]

