version: "2"
run:
  modules-download-mode: vendor
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - wastedassign
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"  # Disable quickfix suggestions (new in v2)
        - "-ST*"  # Disable style checks (new in v2)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
