FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
WORKDIR /go/src/github.com/openshift/cluster-network-operator
COPY . .
RUN hack/build-go.sh; \
    mkdir -p /tmp/build; \
    cp /go/src/github.com/openshift/cluster-network-operator/_output/linux/$(go env GOARCH)/cluster-network-operator /tmp/build/; \
    cp /go/src/github.com/openshift/cluster-network-operator/_output/linux/$(go env GOARCH)/cluster-network-renderer /tmp/build/; \
    cp /go/src/github.com/openshift/cluster-network-operator/_output/linux/$(go env GOARCH)/cluster-network-check-endpoints /tmp/build/

FROM registry.svc.ci.openshift.org/ocp/4.7:base
COPY --from=builder /tmp/build/cluster-network-operator /usr/bin/
COPY --from=builder /tmp/build/cluster-network-renderer /usr/bin/
COPY --from=builder /tmp/build/cluster-network-check-endpoints /usr/bin
COPY manifests /manifests
COPY bindata /bindata
ENV OPERATOR_NAME=cluster-network-operator
CMD ["/usr/bin/cluster-network-operator"]
LABEL io.openshift.release.operator true
