apiVersion: "networkoperator.openshift.io/v1"
kind: "NetworkConfig"
metadata:
  name: "default"
spec:
  serviceNetwork: "10.3.0.0/16"
  clusterNetworks:
    - cidr: "10.2.0.0/16"
      hostSubnetLength: 9
  defaultNetwork:
    type: OpenshiftSDN
    openshiftSDNConfig:
      mode: Networkpolicy
