---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sriov
  labels:
    name: openshift-sriov
    openshift.io/run-level: "0"
  annotations:
    openshift.io/node-selector: "" #override default node selector
    openshift.io/description: "OpenShift SR-IOV network components"
