---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-sdn
rules:
- apiGroups: ["network.openshift.io"]
  resources:
  - clusternetworks
  - egressnetworkpolicies
  - hostsubnets
  - netnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - endpoints
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: ["extensions"]
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - events
  verbs:
  - create
  - patch
  - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdn
  namespace: openshift-sdn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sdn
subjects:
- kind: ServiceAccount
  name: sdn
  namespace: openshift-sdn

---
# Rather than PATCHing the SecurityContextConstraints object, we can bind to 
# it. This is undocumented, thanks to evb who showed me this trick
# TODO: When the openshift-api control plane is splut out, we will need to
# remove this and replace it with something (sigh) hardcoded
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdn-privileged
roleRef:
  apiVersion: security.openshift.io/v1
  kind: SecurityContextConstraints
  name: privileged
userNames: ["system:serviceaccount:openshift-sdn:sdn"] # needed when binding to scc
groupNames: []
subjects:
- kind: ServiceAccount
  name: sdn
  namespace: openshift-sdn
