---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdn-controller
  namespace: openshift-sdn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-sdn-controller
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - list
  - get
  - watch
- apiGroups: ["network.openshift.io"]
  resources:
  - clusternetworks
  - egressnetworkpolicies
  - hostsubnets
  - netnamespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
- apiGroups: [""]
  resources:
  - "nodes/status"
  verbs:
  - patch
  - update
- apiGroups: ["cloud.network.openshift.io"]
  resources:
  - cloudprivateipconfigs
  verbs:
  - create
  - patch
  - update
  - delete
  - get
  - list
  - watch
- apiGroups: ['authentication.k8s.io']
  resources: ['tokenreviews']
  verbs: ['create']
- apiGroups: ['authorization.k8s.io']
  resources: ['subjectaccessreviews']
  verbs: ['create']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-sdn-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-sdn-controller
subjects:
- kind: ServiceAccount
  name: sdn-controller
  namespace: openshift-sdn

---
# Only grant access to the specific config map for leader election
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-sdn-controller-leaderelection
  namespace: openshift-sdn
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups: ["", "events.k8s.io"]
  resources:
  - events
  verbs:
  - create
  - patch
  - update

---
# Bind leader-election access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-sdn-controller-leaderelection
  namespace: openshift-sdn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-sdn-controller-leaderelection
subjects:
- kind: ServiceAccount
  name: sdn-controller
  namespace: openshift-sdn
