apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sdn
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: monitor-sdn
  namespace: openshift-sdn
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - openshift-sdn
  selector:
    matchLabels:
      app: sdn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdn
  name: sdn
  namespace: openshift-sdn
spec:
  selector:
    app: sdn
  clusterIP: None
  ports:
  - name: metrics
    port: 9101
    protocol: TCP
    targetPort: 9101
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-sdn
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-sdn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
