{{if .InstallOVS}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ovs
  namespace: openshift-sdn
  annotations:
    kubernetes.io/description: |
      This daemon set launches the Open vSwitch daemon.
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      app: ovs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovs
        component: network
        type: infra
        openshift.io/component: network
    spec:
      serviceAccountName: sdn #needed to run privileged pods; not used for api access
      hostNetwork: true
      priorityClassName: system-node-critical
      containers:
      - name: openvswitch
        image: {{.SDNImage}}
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          set -euo pipefail
          export SYSTEMD_IGNORE_CHROOT=yes

          # systemctl cannot be used in a separate PID namespace to reach
          # the systemd running in PID 1. Therefore we need to use the dbus API
          systemctl_restart(){
            gdbus call \
              --system \
              --dest org.freedesktop.systemd1 \
              --object-path /org/freedesktop/systemd1/unit/"$(svc_encode_name ${1})"_2eservice \
              --method org.freedesktop.systemd1.Unit.Restart "replace"
          }
          svc_encode_name(){
            # systemd encodes some characters, so far we only need to encode
            # the character "-" but there may be more in the future.
            echo "${1//-/_2d}"
          }

          # Check to see if ovs is provided by the node:
          if [ -f /host/var/run/ovs-config-executed ]; then
            echo "openvswitch is running in systemd"
            # In some very strange corner cases, the owner for /run/openvswitch
            # can be wrong, so we need to clean up and restart.
            ovs_uid=$(chroot /host id -u openvswitch)
            ovs_gid=$(chroot /host id -g openvswitch)
            chown -R "${ovs_uid}:${ovs_gid}" /run/openvswitch
            if [[ ! -S /run/openvswitch/db.sock ]]; then
              systemctl_restart ovsdb-server
            fi
            # Don't need to worry about restoring flows; this can only change if we've rebooted
            exec tail -F /host/var/log/openvswitch/ovs-vswitchd.log /host/var/log/openvswitch/ovsdb-server.log
          else
            echo "openvswitch is running in container"
            # if another process is listening on the cni-server socket, wait until it exits
            retries=0
            while true; do
              if /usr/share/openvswitch/scripts/ovs-ctl status &>/dev/null; then
                echo "warning: Another process is currently managing OVS, waiting 15s ..." 2>&1
                sleep 15 & wait
                (( retries += 1 ))
              else
                break
              fi
              if [[ "${retries}" -gt 40 ]]; then
                echo "error: Another process is currently managing OVS, exiting" 2>&1
                exit 1
              fi
            done

            function quit {
                # Save the flows
                echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Saving flows ..." 2>&1
                bridges=$(ovs-vsctl -- --real list-br)
                TMPDIR=/var/run/openvswitch /usr/share/openvswitch/scripts/ovs-save save-flows $bridges > /var/run/openvswitch/flows.sh
                echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Saved flows" 2>&1

                # Don't allow ovs-vswitchd to clear datapath flows on exit
                kill -9 $(cat /var/run/openvswitch/ovs-vswitchd.pid 2>/dev/null) 2>/dev/null || true
                kill $(cat /var/run/openvswitch/ovsdb-server.pid 2>/dev/null) 2>/dev/null || true
                exit 0
            }
            trap quit SIGTERM

            function deletePid {
                rm /var/run/openvswitch/ovs-vswitchd.pid
                rm /var/run/openvswitch/ovsdb-server.pid
            }
            trap deletePid EXIT

            chown -R openvswitch:openvswitch /var/run/openvswitch
            chown -R openvswitch:openvswitch /etc/openvswitch

            # launch OVS
            # Start the ovsdb so that we can prep it before we start the ovs-vswitchd
            /usr/share/openvswitch/scripts/ovs-ctl start --ovs-user=openvswitch:openvswitch --no-ovs-vswitchd --system-id=random --no-monitor

            # Set the flow-restore-wait to true so ovs-vswitchd will wait till flows are restored
            ovs-vsctl --no-wait set Open_vSwitch . other_config:flow-restore-wait=true

            # Restrict the number of pthreads ovs-vswitchd creates to reduce the
            # amount of RSS it uses on hosts with many cores
            # https://bugzilla.redhat.com/show_bug.cgi?id=1571379
            # https://bugzilla.redhat.com/show_bug.cgi?id=1572797
            if [[ `nproc` -gt 12 ]]; then
                ovs-vsctl --no-wait set Open_vSwitch . other_config:n-revalidator-threads=4
                ovs-vsctl --no-wait set Open_vSwitch . other_config:n-handler-threads=10
            fi

            # And finally start the ovs-vswitchd now the DB is prepped
            /usr/share/openvswitch/scripts/ovs-ctl start --ovs-user=openvswitch:openvswitch --no-ovsdb-server --system-id=random --no-monitor

            # Load any flows that we saved
            echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Loading previous flows ..." 2>&1
            if [[ -f /var/run/openvswitch/flows.sh ]]; then
              echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Adding br0 if it doesn't exist ..." 2>&1
              /usr/bin/ovs-vsctl --may-exist add-br br0 -- set Bridge br0 fail_mode=secure protocols=OpenFlow13
              echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Created br0, now adding flows ..." 2>&1
              mv /var/run/openvswitch/flows.sh /var/run/openvswitch/flows-old.sh
              sh -x /var/run/openvswitch/flows-old.sh
              echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Done restoring the existing flows ..." 2>&1
              rm /var/run/openvswitch/flows-old.sh
            fi

            echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Remove other config ..." 2>&1
            ovs-vsctl --no-wait --if-exists remove Open_vSwitch . other_config flow-restore-wait=true
            echo "$(date -u "+%Y-%m-%d %H:%M:%S") info: Removed other config ..." 2>&1

            tail -F --pid=$(cat /var/run/openvswitch/ovs-vswitchd.pid) /var/log/openvswitch/ovs-vswitchd.log &
            tail -F --pid=$(cat /var/run/openvswitch/ovsdb-server.pid) /var/log/openvswitch/ovsdb-server.log &
            wait
          fi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: host-modules
          readOnly: true
        - mountPath: /run
          name: host-run
        - mountPath: /sys
          name: host-sys
          readOnly: true
        - mountPath: /etc/openvswitch
          name: host-config-openvswitch
        - mountPath: /host
          name: host-slash
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        terminationMessagePolicy: FallbackToLogsOnError
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              /usr/bin/ovs-vsctl -t 5 show > /dev/null
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 6
        terminationGracePeriodSeconds: 45
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network.operator.openshift.io/external-openvswitch
                operator: DoesNotExist
      volumes:
      - name: host-modules
        hostPath:
          path: /lib/modules
      - name: host-run
        hostPath:
          path: /run
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-config-openvswitch
        hostPath:
          path: /var/lib/openvswitch
          type: DirectoryOrCreate
      - name: host-slash
        hostPath:
          path: /
      tolerations:
      - operator: "Exists"
{{- end}}
