apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.AdditionalNetworkName}}
  namespace: {{getOr . "AdditionalNetworkNamespace" "default"}}
spec:
  config: |-
{{.AdditionalNetworkConfig | indent 4}}
