apiVersion: v1
kind: Service
metadata:
  name: network-node-identity
  namespace: {{.HostedClusterNamespace}}
  labels:
    app: network-node-identity
    hypershift.openshift.io/allow-guest-webhooks: "true"
  annotations:
    network.operator.openshift.io/cluster-name: {{.ManagementClusterName}}
    service.alpha.openshift.io/serving-cert-secret-name: network-node-identity-secret
spec:
  ports:
    - name: webhook
      port: {{.NetworkNodeIdentityPort}}
      targetPort: {{.NetworkNodeIdentityPort}}
  selector:
    app: network-node-identity
