---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ovnkube-control-plane
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: monitor-ovn-control-plane-metrics
  namespace: openshift-ovn-kubernetes
spec:
  endpoints:
  - interval: 30s
    port: metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: ovn-kubernetes-control-plane.openshift-ovn-kubernetes.svc
  jobLabel: app
  namespaceSelector:
    matchNames:
    - openshift-ovn-kubernetes
  selector:
    matchLabels:
      app: ovnkube-control-plane
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovnkube-control-plane
  name: ovn-kubernetes-control-plane
  namespace: openshift-ovn-kubernetes
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ovn-control-plane-metrics-cert
spec:
  selector:
    app: ovnkube-control-plane
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: metrics
    port: 9106
    protocol: TCP
    targetPort: 9106
  sessionAffinity: None
  type: ClusterIP
