---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtu-prober 
  namespace: openshift-network-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-network-operator
  name: mtu-prober
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - create
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-network-operator
  name: mtu-prober
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mtu-prober
subjects:
- kind: ServiceAccount
  name: mtu-prober