---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: multus
data:
  cni-conf.json: |-
{{.NodeConfig | indent 4}}

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: multus
  namespace: multus
  annotations:
    kubernetes.io/description: |
      This daemon set launches the Multus networking components.
spec:
  selector:
    matchLabels:
      app: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: multus
        component: network
        type: infra
        openshift.io/component: network
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      serviceAccountName: multus
      containers:
      - name: multus
        image: nfvpe/multus:latest
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /usr/src/multus-cni/images
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf
