apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-network-operator
  namespace: openshift-cluster-network-operator
  labels:
    k8s-app: cluster-network-operator
spec:
  selector:
    matchLabels:
      k8s-app: cluster-network-operator
  template:
    metadata:
      labels:
        k8s-app: cluster-network-operator
    spec:
      containers:
      - name: cluster-network-operator
        image: docker.io/openshift/origin-cluster-network-operator:v4.0.0
        command:
        - /bin/cluster-network-operator
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
        env:
        - name: SDN_IMAGE
          value: "docker.io/openshift/origin-node:v4.0.0"
        - name: KUBERNETES_SERVICE_PORT # allows CVO to communicate with apiserver directly on same host.
          value: "6443"
        - name: KUBERNETES_SERVICE_HOST # allows CVO to communicate with apiserver directly on same host.
          value: "127.0.0.1"
        - name: POD_NAME # The operator-sdk needs to know the pod name, but we're host network
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
