apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/serving-cert-secret-name: metrics-tls
  name: metrics
  namespace: openshift-network-operator
  labels:
    name: network-operator
spec:
  ports:
  - name: metrics
    port: 9104
    targetPort: cno
  selector:
    name: network-operator
  type: ClusterIP
  clusterIP: None
