apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: network-operator
  namespace: openshift-network-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: metrics.openshift-network-operator.svc
  jobLabel: component
  selector:
    matchLabels:
      name: network-operator
