---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovn-kubernetes-node
  namespace: openshift-ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-ovn-kubernetes-node-limited
  namespace: openshift-ovn-kubernetes
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
  # the name change is required to ensure that both bindings exist during upgrade to avoid disruptions
  name: openshift-ovn-kubernetes-nodes-identity-limited
{{ else }}
  name: openshift-ovn-kubernetes-node-limited
{{ end }}
  namespace: openshift-ovn-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-ovn-kubernetes-node-limited
subjects:
{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
- kind: Group
  name: system:ovn-nodes
  apiGroup: rbac.authorization.k8s.io
{{ else }}
- kind: ServiceAccount
  name: ovn-kubernetes-node
  namespace: openshift-ovn-kubernetes
{{ end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-ovn-kubernetes-node-limited
rules:
- apiGroups: [""]
  resources:
  - pods/status
  - nodes/status
  verbs:
  - patch
  - update
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups: ["", "events.k8s.io"]
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups: ["apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
- apiGroups: [certificates.k8s.io]
  resources: ['certificatesigningrequests']
  verbs:
    - create
    - get
    - list
- apiGroups: ["security.openshift.io"]
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups: ["k8s.ovn.org"]
  resources:
  - adminpolicybasedexternalroutes
  - egressfirewalls
  - egressips
  - egressqoses
  - egressservices
  - egressservices/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
{{- if .OVN_ADMIN_NETWORK_POLICY_ENABLE }}
- apiGroups: ["policy.networking.k8s.io"]
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups: ["policy.networking.k8s.io"]
  resources:
  - adminnetworkpolicies/status
  - baselineadminnetworkpolicies/status
  verbs:
  - update
{{- end }}
- apiGroups: ["cloud.network.openshift.io"]
  resources:
  - cloudprivateipconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  - multi-networkpolicies
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
  # the name change is required to ensure that both bindings exist during upgrade to avoid disruptions
  name: openshift-ovn-kubernetes-node-identity-limited
{{ else }}
  name: openshift-ovn-kubernetes-node-limited
{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-ovn-kubernetes-node-limited
subjects:
{{ if .NETWORK_NODE_IDENTITY_ENABLE }}
- kind: Group
  name: system:ovn-nodes
  apiGroup: rbac.authorization.k8s.io
{{ else }}
- kind: ServiceAccount
  name: ovn-kubernetes-node
  namespace: openshift-ovn-kubernetes
{{ end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-ovn-kubernetes-kube-rbac-proxy
rules:
  - apiGroups: ['authentication.k8s.io']
    resources: ['tokenreviews']
    verbs: ['create']
  - apiGroups: ['authorization.k8s.io']
    resources: ['subjectaccessreviews']
    verbs: ['create']

---
# openshift-ovn-kubernetes-kube-rbac-proxy cluster role is bound to ovn-kubernetes-node service account even if NETWORK_NODE_IDENTITY_ENABLE is true.
# The kube-rbac-proxy-node container continues to use the service account instead of the per-node certificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-ovn-kubernetes-node-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-ovn-kubernetes-kube-rbac-proxy
subjects:
- kind: ServiceAccount
  name: ovn-kubernetes-node
  namespace: openshift-ovn-kubernetes
