---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovn-kubernetes-control-plane
  namespace: openshift-ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-ovn-kubernetes-control-plane-limited
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups: ["", "events.k8s.io"]
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups: ["security.openshift.io"]
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups: [""]
  resources:
  - nodes/status
  - pods/status
  verbs:
  - patch
  - update
- apiGroups: [""]
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["k8s.ovn.org"]
  resources:
  - egressips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["k8s.ovn.org"]
  resources:
    - adminpolicybasedexternalroutes
    - egressfirewalls
    - egressqoses
    - egressservices
  verbs:
    - get
    - list
    - watch
- apiGroups: ["k8s.ovn.org"]
  resources:
  - adminpolicybasedexternalroutes/status
  - egressfirewalls/status
  - egressqoses/status
  verbs:
  - patch
- apiGroups: ["policy.networking.k8s.io"]
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - list
- apiGroups: ["policy.networking.k8s.io"]
  resources:
  - adminnetworkpolicies/status
  - baselineadminnetworkpolicies/status
  verbs:
  - patch
- apiGroups: ["k8s.ovn.org"]
  resources:
    - egressservices/status
  verbs:
    - update
{{- if .DNS_NAME_RESOLVER_ENABLE }}
- apiGroups: ["network.openshift.io"]
  resources:
  - dnsnameresolvers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
- apiGroups: ["cloud.network.openshift.io"]
  resources:
  - cloudprivateipconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
- apiGroups: ['authentication.k8s.io']
  resources: ['tokenreviews']
  verbs: ['create']
- apiGroups: ['authorization.k8s.io']
  resources: ['subjectaccessreviews']
  verbs: ['create']
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  - multi-networkpolicies
  verbs: ["list", "get", "watch"]
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - patch
- apiGroups:
    - k8s.cni.cncf.io
  resources:
    - ipamclaims
  verbs: ["list", "get", "watch"]
- apiGroups:
  - "k8s.cni.cncf.io"
  resources:
    - ipamclaims/status
  verbs: [ "patch", "update" ]
- apiGroups:
    - discovery.k8s.io
  resources:
    - endpointslices
  verbs:
    - create
    - delete
    - update
    - get
    - list
    - watch
- apiGroups: [""]
  resources:
    - services/finalizers
  verbs:
    - update
- apiGroups: ["k8s.ovn.org"]
  resources:
    - userdefinednetworks
    - clusteruserdefinednetworks
  verbs:
    - get
    - list
    - watch
- apiGroups: ["k8s.ovn.org"]
  resources:
    - userdefinednetworks
    - userdefinednetworks/status
    - clusteruserdefinednetworks
    - clusteruserdefinednetworks/status
  verbs:
    - patch
    - update
- apiGroups: [ "k8s.ovn.org" ]
  resources:
    - userdefinednetworks/finalizers
    - clusteruserdefinednetworks/finalizers
  verbs:
    - update
- apiGroups: [ "k8s.cni.cncf.io" ]
  resources:
    - network-attachment-definitions
  verbs:
    - update
    - create
    - delete
- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
{{- if .OVN_ROUTE_ADVERTISEMENTS_ENABLE }}
- apiGroups:
  - k8s.ovn.org
  resources:
  - routeadvertisements
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - k8s.ovn.org
  resources:
  - routeadvertisements/status
  verbs:
  - patch
  - update
- apiGroups: 
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - list
  - get
  - watch
  - create
  - delete
  - update
  - patch
{{- end}}
{{- if .OVN_EVPN_ENABLE }}
- apiGroups:
  - k8s.ovn.org
  resources:
  - vteps
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - k8s.ovn.org
  resources:
  - vteps/status
  verbs:
  - patch
  - update
{{- end}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-ovn-kubernetes-control-plane-limited
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-ovn-kubernetes-control-plane-limited
subjects:
- kind: ServiceAccount
  name: ovn-kubernetes-control-plane
  namespace: openshift-ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-ovn-kubernetes-control-plane-limited
  namespace: openshift-ovn-kubernetes
rules:
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-ovn-kubernetes-control-plane-limited
  namespace: openshift-ovn-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-ovn-kubernetes-control-plane-limited
subjects:
- kind: ServiceAccount
  name: ovn-kubernetes-control-plane
  namespace: openshift-ovn-kubernetes
