---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: openshift-ovn-kubernetes-cluster-reader
rules:
- apiGroups: ["k8s.ovn.org"]
  resources:
  - egressfirewalls
  - egressips
  - egressqoses
  - egressservices
  - adminpolicybasedexternalroutes
  - userdefinednetworks
  verbs:
  - get
  - list
  - watch
{{- if .DNS_NAME_RESOLVER_ENABLE }}
- apiGroups: ["network.openshift.io"]
  resources:
  - dnsnameresolvers
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups: ["policy.networking.k8s.io"]
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - get
  - list
  - watch
