apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: networking-rules
  namespace: openshift-ovn-kubernetes
spec:
  groups:
  - name: cluster-network-operator-ovn.rules
    rules:
    - alert: NodeWithoutOVNKubeNodePodRunning
      annotations:
        summary: All Linux nodes should be running an ovnkube-node pod, {{"{{"}} $labels.node {{"}}"}} is not.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/cluster-network-operator/NodeWithoutOVNKubeNodePodRunning.md
        description: |
          Networking is degraded on nodes that do not have a functioning ovnkube-node pod. Existing workloads on the
          node may continue to have connectivity but any additional workloads will not be provisioned on the node. Any
          network policy changes will not be implemented on existing workloads on the node.
      expr: |
        (kube_node_info unless on(node) (kube_pod_info{namespace="openshift-ovn-kubernetes",pod=~"ovnkube-node.*"}
        or kube_node_labels{label_kubernetes_io_os="windows"})) > 0
      for: 20m
      labels:
        severity: warning
    - alert: OVNKubernetesControllerDisconnectedSouthboundDatabase
      annotations:
        summary: Networking control plane is degraded on node {{"{{"}} $labels.node {{"}}"}} because OVN controller is not connected to OVN southbound database.
        # runbook_url: TODO by https://issues.redhat.com/browse/SDN-3444
        description: |
          Networking is degraded on nodes when OVN controller is not connected to OVN southbound database connection. No networking control plane updates will be applied to the node.
      expr: |
        max_over_time(ovn_controller_southbound_database_connected[5m]) == 0
      labels:
        severity: warning
