apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: networking-rules
  namespace: openshift-ovn-kubernetes
spec:
  groups:
  - name: cluster-network-operator-ovn.rules
    rules:
    - alert: NodeWithoutOVNKubeNodePodRunning
      annotations:
        summary: All Linux nodes should be running an ovnkube-node pod, {{"{{"}} $labels.node {{"}}"}} is not.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/cluster-network-operator/NodeWithoutOVNKubeNodePodRunning.md
        description: |
          Networking is degraded on nodes that do not have a functioning ovnkube-node pod. Existing workloads on the
          node may continue to have connectivity but any changes to the networking control plane will not be implemented.
      expr: |
        (kube_node_info unless on(node) (kube_pod_info{namespace="openshift-ovn-kubernetes",pod=~"ovnkube-node.*"}
        or kube_node_labels{label_kubernetes_io_os="windows"})) > 0
      for: 20m
      labels:
        severity: warning
    - alert: OVNKubernetesControllerDisconnectedSouthboundDatabase
      annotations:
        summary: Networking control plane is degraded on node {{"{{"}} $labels.node {{"}}"}} because OVN controller is not connected to OVN southbound database.
        # runbook_url: TODO by https://issues.redhat.com/browse/SDN-3444
        description: |
          Networking is degraded on nodes when OVN controller is not connected to OVN southbound database connection. No networking control plane updates will be applied to the node.
      expr: |
        max_over_time(ovn_controller_southbound_database_connected[5m]) == 0
      for: 10m
      labels:
        severity: warning
    - alert: OVNKubernetesNodePodAddError
      annotations:
        summary: OVN Kubernetes is experiencing pod creation errors at an elevated rate.
        description: OVN Kubernetes experiences pod creation errors at an elevated rate. The
          pods will be retried.
      expr: |
        (sum by(instance, namespace) (rate(ovnkube_node_cni_request_duration_seconds_count{command="ADD",err="true"}[5m]))
          /
        sum by(instance, namespace) (rate(ovnkube_node_cni_request_duration_seconds_count{command="ADD"}[5m])))
        > 0.1
      for: 15m
      labels:
        severity: warning
    - alert: OVNKubernetesNodePodDeleteError
      annotations:
        summary: OVN Kubernetes experiencing pod deletion errors at an elevated rate.
        description: OVN Kubernetes experiences pod deletion errors at an elevated rate. The
          pods will be retried.
      expr: |
        (sum by(instance, namespace) (rate(ovnkube_node_cni_request_duration_seconds_count{command="DEL",err="true"}[5m]))
          /
        sum by(instance, namespace) (rate(ovnkube_node_cni_request_duration_seconds_count{command="DEL"}[5m])))
        > 0.1
      for: 15m
      labels:
        severity: warning
    - alert: OVNKubernetesResourceRetryFailure
      annotations:
        summary: OVN Kubernetes failed to apply networking control plane configuration.
        description: |
          OVN Kubernetes failed to apply networking control plane configuration after several attempts. This might be because the configuration
          provided by the user is invalid or because of an internal error. As a consequence, the cluster might have a degraded status.
      expr: increase(ovnkube_resource_retry_failures_total[10m]) > 0
      labels:
        severity: warning
    - alert: OVNKubernetesNodeOVSOverflowUserspace
      annotations:
        summary: OVS vSwitch daemon drops packets due to buffer overflow.
        description: Netlink messages dropped by OVS vSwitch daemon due to netlink socket buffer overflow.
          This will result in packet loss.
      expr: increase(ovs_vswitchd_netlink_overflow[5m]) > 0
      for: 15m
      labels:
        severity: warning
    - alert: OVNKubernetesNodeOVSOverflowKernel
      annotations:
        summary: OVS kernel module drops packets due to buffer overflow.
        description: Netlink messages dropped by OVS kernel module due to netlink socket buffer overflow.
          This will result in packet loss.
      expr: increase(ovs_vswitchd_dp_flows_lookup_lost[5m]) > 0
      for: 15m
      labels:
        severity: warning
