kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  apiServerAddress: 192.168.1.5
  apiServerPort: 11337
nodes:
 - role: control-plane
   extraMounts:
     - hostPath: /tmp/kind
       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
# - role: control-plane
#   extraMounts:
#     - hostPath: /tmp/kind
#       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
# - role: control-plane
#   extraMounts:
#     - hostPath: /tmp/kind
#       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
# - role: worker
#   extraMounts:
#     - hostPath: /tmp/kind
#       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
# - role: worker
#   extraMounts:
#     - hostPath: /tmp/kind
#       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/

