---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuryr-controller
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - endpoints
  - services
  - services/status
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups: ["openstack.org"]
  resources:
  - kuryrnetworks
  - kuryrnetworkpolicies
  - kuryrports
  - kuryrloadbalancers
  verbs: ["*"]
- apiGroups: ["security.openshift.io"]
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups: ["machine.openshift.io"]
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups: ["", "events.k8s.io"]
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuryr-daemon
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups: ["openstack.org"]
  resources:
  - kuryrports
  verbs:
  - get
  - watch
  - list
- apiGroups: ["security.openshift.io"]
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups: ["", "events.k8s.io"]
  resources:
  - events
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuryr-controller
  namespace: openshift-kuryr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuryr-daemon
  namespace: openshift-kuryr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuryr-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuryr-controller
subjects:
- kind: ServiceAccount
  name: kuryr-controller
  namespace: openshift-kuryr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuryr-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuryr-daemon
subjects:
- kind: ServiceAccount
  name: kuryr-daemon
  namespace: openshift-kuryr
