apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuryrnets.openstack.org
spec:
  group: openstack.org
  version: v1
  scope: Cluster
  names:
    plural: kuryrnets
    singular: kuryrnet
    kind: KuryrNet
  additionalPrinterColumns:
    - name: SUBNET-CIDR
      type: string
      description: The subnet CIDR allocated to the namespace
      JSONPath: .spec.subnetCIDR
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - netId
          - routerId
          - subnetCIDR
          - subnetId
          properties:
            netId:
              type: string
            populated:
              type: boolean
            routerId:
              type: string
            sgId:
              type: string
            subnetCIDR:
              type: string
            subnetId:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuryrnetpolicies.openstack.org
spec:
  group: openstack.org
  version: v1
  scope: Namespaced
  names:
    plural: kuryrnetpolicies
    singular: kuryrnetpolicy
    kind: KuryrNetPolicy
    shortNames:
      - knp
  additionalPrinterColumns:
    - name: SG-ID
      type: string
      description: The ID of the SG associated to the policy
      JSONPath: .spec.securityGroupId
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - egressSgRules
          - ingressSgRules
          - networkpolicy_spec
          - podSelector
          - securityGroupId
          properties:
            egressSgRules:
              type: array
              items:
                type: object
                required:
                - security_group_rule
                properties:
                  remote_ip_prefixes:
                    type: object
                  namespace:
                    type: string
                  security_group_rule:
                    type: object
                    required:
                    - id
                    properties:
                      description:
                        type: string
                      direction:
                        type: string
                      ethertype:
                        type: string
                      id:
                        type: string
                      port_range_max:
                        type: integer
                      port_range_min:
                        type: integer
                      protocol:
                        type: string
                      remote_ip_prefix:
                        type: string
                      security_group_id:
                        type: string
            ingressSgRules:
              type: array
              items:
                type: object
                required:
                - security_group_rule
                properties:
                  remote_ip_prefixes:
                    type: object
                  namespace:
                    type: string
                  security_group_rule:
                    type: object
                    required:
                    - id
                    properties:
                      description:
                        type: string
                      direction:
                        type: string
                      ethertype:
                        type: string
                      id:
                        type: string
                      port_range_max:
                        type: integer
                      port_range_min:
                        type: integer
                      protocol:
                        type: string
                      remote_ip_prefix:
                        type: string
                      security_group_id:
                        type: string
            networkpolicy_spec:
              type: object
              properties:
                podSelector:
                  type: object
                policyTypes:
                  type: array
                ingress:
                  type: array
                egress:
                  type: array
            podSelector:
              type: object
            securityGroupId:
              type: string
            securityGroupName:
              type: string
