{{if .AdmissionController}}
apiVersion: v1
kind: Service
metadata:
  name: kuryr-dns-admission-controller
  namespace: openshift-kuryr
  labels:
    app: kuryr-dns-admission-controller
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: kuryr-dns-admission-controller
{{- end}}
