// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertSpec) DeepCopyInto(out *CertSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertSpec.
func (in *CertSpec) DeepCopy() *CertSpec {
	if in == nil {
		return nil
	}
	out := new(CertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRouter) DeepCopyInto(out *EgressRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = make([]EgressRouterStatus, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRouter.
func (in *EgressRouter) DeepCopy() *EgressRouter {
	if in == nil {
		return nil
	}
	out := new(EgressRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRouterList) DeepCopyInto(out *EgressRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EgressRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRouterList.
func (in *EgressRouterList) DeepCopy() *EgressRouterList {
	if in == nil {
		return nil
	}
	out := new(EgressRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRouterSpec) DeepCopyInto(out *EgressRouterSpec) {
	*out = *in
	out.InterfaceArgs = in.InterfaceArgs
	in.IP.DeepCopyInto(&out.IP)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRouterSpec.
func (in *EgressRouterSpec) DeepCopy() *EgressRouterSpec {
	if in == nil {
		return nil
	}
	out := new(EgressRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRouterStatus) DeepCopyInto(out *EgressRouterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRouterStatus.
func (in *EgressRouterStatus) DeepCopy() *EgressRouterStatus {
	if in == nil {
		return nil
	}
	out := new(EgressRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigObject) DeepCopyInto(out *IPConfigObject) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]IPAddress, len(*in))
		copy(*out, *in)
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]DestinationCIDR, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigObject.
func (in *IPConfigObject) DeepCopy() *IPConfigObject {
	if in == nil {
		return nil
	}
	out := new(IPConfigObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceArgsObject) DeepCopyInto(out *InterfaceArgsObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceArgsObject.
func (in *InterfaceArgsObject) DeepCopy() *InterfaceArgsObject {
	if in == nil {
		return nil
	}
	out := new(InterfaceArgsObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorPKI) DeepCopyInto(out *OperatorPKI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorPKI.
func (in *OperatorPKI) DeepCopy() *OperatorPKI {
	if in == nil {
		return nil
	}
	out := new(OperatorPKI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorPKI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorPKIList) DeepCopyInto(out *OperatorPKIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatorPKI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorPKIList.
func (in *OperatorPKIList) DeepCopy() *OperatorPKIList {
	if in == nil {
		return nil
	}
	out := new(OperatorPKIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorPKIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorPKISpec) DeepCopyInto(out *OperatorPKISpec) {
	*out = *in
	out.TargetCert = in.TargetCert
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorPKISpec.
func (in *OperatorPKISpec) DeepCopy() *OperatorPKISpec {
	if in == nil {
		return nil
	}
	out := new(OperatorPKISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorPKIStatus) DeepCopyInto(out *OperatorPKIStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorPKIStatus.
func (in *OperatorPKIStatus) DeepCopy() *OperatorPKIStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorPKIStatus)
	in.DeepCopyInto(out)
	return out
}
