---
{{- if eq .RHOBSMonitoring "1" }}
apiVersion: monitoring.rhobs/v1
{{- else }}
apiVersion: monitoring.coreos.com/v1
{{- end }}
kind: ServiceMonitor
metadata:
  labels:
    app: ovnkube-master
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
  name: monitor-ovn-master-metrics
  namespace: {{.HostedClusterNamespace}}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: https
    bearerTokenSecret:
      key: ""
    tlsConfig:
      ca:
        configMap:
          key: service-ca.crt
          name: openshift-service-ca.crt
      cert:
        secret:
          key: tls.crt
          name: ovn-master-metrics-cert
      keySecret:
        key: tls.key
        name: ovn-master-metrics-cert
      serverName: ovnkube-master-internal.{{.HostedClusterNamespace}}.svc
    metricRelabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
    relabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
  - interval: 30s
    port: metrics-cm
    scheme: https
    bearerTokenSecret:
      key: ""
    tlsConfig:
      ca:
        configMap:
          key: service-ca.crt
          name: openshift-service-ca.crt
      cert:
        secret:
          key: tls.crt
          name: ovn-master-metrics-cert
      keySecret:
        key: tls.key
        name: ovn-master-metrics-cert
      serverName: ovnkube-master-internal.{{.HostedClusterNamespace}}.svc
    metricRelabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
    relabelings:
    - action: replace
      replacement: {{.ClusterID}}
      targetLabel: {{.ClusterIDLabel}}
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{.HostedClusterNamespace}}
  selector:
    matchLabels:
      app: ovnkube-master
---
apiVersion: v1
kind: Service
metadata:
  name: ovnkube-master-internal
  namespace: {{.HostedClusterNamespace}}
  annotations:
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
    service.beta.openshift.io/serving-cert-secret-name: ovn-master-metrics-cert
  labels:
    app: ovnkube-master
spec:
  selector:
    app: ovnkube-master
  publishNotReadyAddresses: true
  ports:
  - name: north
    port: {{.OVN_NB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_NB_PORT}}
  - name: south
    port: {{.OVN_SB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_SB_PORT}}
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  - name: metrics-cm
    port: 9108
    protocol: TCP
    targetPort: 9108
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP
