---
apiVersion: v1
kind: Service
metadata:
  name: multus-admission-controller
  namespace: {{.AdmissionControllerNamespace}}
  labels:
    app: multus-admission-controller
  annotations:
{{- if .HyperShiftEnabled}}
    network.operator.openshift.io/cluster-name: {{.ManagementClusterName}}
{{- end }}
    service.alpha.openshift.io/serving-cert-secret-name: multus-admission-controller-secret
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 6443
  - name: metrics
    port: 8443
    targetPort: https
  selector:
    app: multus-admission-controller
