---
apiVersion: v1
kind: Service
metadata:
  name: multus-admission-controller
  namespace: openshift-multus
  labels:
    app: multus-admission-controller
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: multus-admission-controller-secret
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 6443
  - name: metrics
    port: 8443
    targetPort: https
  selector:
    app: multus-admission-controller
