---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{.MultusValidatingWebhookName}}
  labels:
    app: multus-admission-controller
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: multus-validating-config.k8s.io
    clientConfig:
      service:
        name: multus-admission-controller
        namespace: openshift-multus
        path: "/validate"
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["k8s.cni.cncf.io"]
        apiVersions: ["v1"]
        resources: ["network-attachment-definitions"]
