---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.ServiceCAConfigMap}}
  namespace: openshift-network-operator
  labels:
    app: multus-admission-controller
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
