---
{{- if eq .RHOBSMonitoring "1" }}
apiVersion: monitoring.rhobs/v1
{{- else }}
apiVersion: monitoring.coreos.com/v1
{{- end }}
kind: ServiceMonitor
metadata:
  labels:
    name: monitor-multus-admission-controller
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
{{- if .HyperShiftEnabled}}
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
{{- end }}
  name: monitor-multus-admission-controller
  namespace: {{.AdmissionControllerNamespace}}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: 'https'
{{- if .HyperShiftEnabled}}
    bearerTokenSecret:
      key: ""
    tlsConfig:
      ca:
        configMap:
          key: {{.CAConfigMapKey}}
          name: {{.CAConfigMap}}
      cert:
        secret:
          key: tls.crt
          name: multus-admission-controller-secret
      keySecret:
        key: tls.key
        name: multus-admission-controller-secret
      serverName: multus-admission-controller.{{.AdmissionControllerNamespace}}.svc
    metricRelabelings:
      - action: replace
        replacement: {{.ClusterID}}
        targetLabel: {{.ClusterIDLabel}}
    relabelings:
      - action: replace
        replacement: {{.ClusterID}}
        targetLabel: {{.ClusterIDLabel}}
{{ else }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: multus-admission-controller.{{.AdmissionControllerNamespace}}.svc
{{- end }}

  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{.AdmissionControllerNamespace}}
  selector:
    matchLabels:
      app: multus-admission-controller
  serviceDiscoveryRole: EndpointSlice
{{- if not .HyperShiftEnabled}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: {{.AdmissionControllerNamespace}}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: {{.AdmissionControllerNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
{{- end }}
