apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: prometheus-k8s-rules
  namespace: openshift-multus
spec:
  groups:
  - name: multus-admission-controller-monitor-service.rules
    rules:
    - expr: |
        max  (network_attachment_definition_enabled_instance_up) by (networks)
      record: cluster:network_attachment_definition_enabled_instance_up:max
    - expr: |
       max  (network_attachment_definition_instances) by (networks)
      record: cluster:network_attachment_definition_instances:max
    - alert: DummyAlert
      annotations:
        summary: Who cares!
      expr: |
        changes(totalReconcilerSuccess[60m]) > 0
      labels:
        severity: critical