apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-node-identity
  namespace: openshift-network-node-identity

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-node-identity
roleRef:
  name: network-node-identity
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: network-node-identity
    namespace: openshift-network-node-identity

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-node-identity
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["get", "list", "watch"]
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests/approval
    verbs: ["update"]
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch", "update"]
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kube-apiserver-client
    verbs: ["approve"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-node-identity-leases
  namespace: openshift-network-node-identity
roleRef:
  name: network-node-identity-leases
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: network-node-identity
    namespace: openshift-network-node-identity

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-network-node-identity
  name: network-node-identity-leases
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
