apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:hostnetwork-v2
  namespace: openshift-network-node-identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork-v2
subjects:
- kind: ServiceAccount
  name: network-node-identity
  namespace: openshift-network-node-identity
