# Request that the cluster network operator PKI controller
# creates a certificate and key for network-node-identity webhook.
apiVersion: network.operator.openshift.io/v1
kind: OperatorPKI
metadata:
  name: network-node-identity
  namespace: openshift-network-node-identity
spec:
  targetCert:
    commonName: {{.NetworkNodeIdentityAddress}}
