kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-config
  namespace: ovn-kubernetes
data:
  net_cidr: "{{ .net_cidr }}"
  svc_cidr: "{{ .svc_cidr }}"
  k8s_apiserver: "https://{{ .KUBERNETES_SERVICE_HOST }}:{{ .KUBERNETES_SERVICE_PORT }}"

