---
# service to expose the ovn-master pod
# at present ovn-master is limited to a single instance so
# when the cluster has multiple masters we can get to the
# ovn-master via this service.
apiVersion: v1
kind: Service
metadata:
  name: ovnkube-db
  namespace: openshift-ovn-kubernetes
spec:
  ports:
  - name: north
    port: 9641
    protocol: TCP
    targetPort: 9641
  - name: south
    port: 9642
    protocol: TCP
    targetPort: 9642
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP
