# Request that the cluster network operator PKI controller
# creates a certificate and key for signing requests.
apiVersion: network.operator.openshift.io/v1
kind: OperatorPKI
metadata:
  name: signer
  namespace: openshift-ovn-kubernetes
spec:
  targetCert:
    commonName: ovn-kubernetes-signer
