kind: ConfigMap
apiVersion: v1
metadata:
  name: openshift-network-features
  namespace: openshift-config-managed
  annotations:
    openshift.io/description: |
      Exposes available network features as required by the Console in order to show or hide some form fields.
      If the map or a given property is undefined, the Console won't throw error and will take a default action (show, hide, show with a warning message...).
data:
  policy_egress: "true"
  policy_peer_ipblock_exceptions: "true"
