# ovnkube-master
# daemonset version 4
# starts master daemons, each in a separate container
# it is run on the master node(s)
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ovnkube-master
  # namespace set up by install
  namespace: openshift-ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This daemonset launches the ovn-kubernetes controller (master) networking components.
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ovnkube-master
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ovnkube-master
        component: network
        type: infra
        openshift.io/component: network
        kubernetes.io/os: "linux"
    spec:
      # Requires fairly broad permissions - ability to read all services and network functions as well
      # as all pods.
      serviceAccountName: ovn-kubernetes-controller
      hostNetwork: true
      hostPID: true
      priorityClassName: "system-cluster-critical"
      containers:
      # firewall rules for ovn - assumed to be setup
      # iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6641 -j ACCEPT
      # iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6642 -j ACCEPT
      # ovs flow for ovn (geneve)
      # /usr/share/openvswitch/scripts/ovs-ctl --protocol=udp --dport=6081 enable-protocol

      # run-ovn-northd - v3
      - name: run-ovn-northd
        image: "{{.OvnImage}}"

        command: ["/root/ovnkube.sh", "run-ovn-northd"]

        volumeMounts:
        # ovn db is stored in the pod in /etc/openvswitch (default ovs tool location)
        # and on the host in /var/lib/openvswitch/
        - mountPath: /etc/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/lib/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn-config
          name: ovn-config-mount

        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "4"
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      # end of container

      # nb-ovsdb - v3
      - name: nb-ovsdb
        image: "{{.OvnImage}}"

        command: ["/root/ovnkube.sh", "nb-ovsdb"]

        volumeMounts:
        # ovn db is stored in the pod in /etc/openvswitch (default ovs tool location)
        # and on the host in /var/lib/openvswitch/
        - mountPath: /etc/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/lib/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn-config
          name: ovn-config-mount

        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "4"
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      # end of container

      # sb-ovsdb - v3
      - name: sb-ovsdb
        image: "{{.OvnImage}}"

        command: ["/root/ovnkube.sh", "sb-ovsdb"]

        volumeMounts:
        # ovn db is stored in the pod in /etc/openvswitch (default ovs tool location)
        # and on the host in /var/lib/openvswitch/
        - mountPath: /etc/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/lib/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/kubernetes/
          name: host-var-run-kubernetes
        - mountPath: /var/run/ovn-config
          name: ovn-config-mount

        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "4"
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      # end of container

      - name: ovnkube-master
        image: "{{.OvnImage}}"

        command: ["/root/ovnkube.sh", "ovn-master"]

        volumeMounts:
        # ovn db is stored in the pod in /etc/openvswitch (default ovs tool location)
        # and on the host in /var/lib/openvswitch/
        - mountPath: /etc/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/lib/openvswitch/
          name: host-var-lib-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/kubernetes/
          name: host-var-run-kubernetes
        - mountPath: /var/run/ovn-config
          name: ovn-config-mount
        - mountPath: /var/run/ovnkube-config
          name: ovnkube-config-mount

        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "4"
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      # end of container

      nodeSelector:
        node-role.kubernetes.io/master: ""
        beta.kubernetes.io/os: "linux"
      volumes:
      - name: host-modules
        hostPath:
          path: /lib/modules
      - name: host-var-lib-ovs
        hostPath:
          path: /var/lib/openvswitch
      - name: host-var-run-ovs
        hostPath:
          path: /var/run/openvswitch
      - name: host-var-run-kubernetes
        hostPath:
          path: /var/run/kubernetes
      - configMap:
          name: ovn-config
        name: ovn-config-mount
      - configMap:
          name: ovnkube-config
        name: ovnkube-config-mount

      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
