---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-network-config-controller
  namespace: openshift-cloud-network-config-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-network-config-controller
rules:
- apiGroups: 
  - cloud.network.openshift.io
  resources:
  - cloudprivateipconfigs
  - cloudprivateipconfigs/status
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-network-config-controller
  namespace: openshift-cloud-network-config-controller
rules:
- apiGroups: 
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-network-config-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-network-config-controller
subjects:
- kind: ServiceAccount
  name: cloud-network-config-controller
  namespace: openshift-cloud-network-config-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-cloud-network-config-controller
  name: cloud-network-config-controller-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-network-config-controller
subjects:
- kind: ServiceAccount
  name: cloud-network-config-controller
  namespace: openshift-cloud-network-config-controller