---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-network-config-controller
  namespace: openshift-cloud-network-config-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-network-config-controller
rules:
- apiGroups: 
  - cloud.network.openshift.io
  resources:
  - cloudprivateipconfigs
  - cloudprivateipconfigs/status
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups: 
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-network-config-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-network-config-controller
subjects:
- kind: ServiceAccount
  name: cloud-network-config-controller
  namespace: openshift-cloud-network-config-controller
