apiVersion: apps/v1
kind: Deployment
metadata:
  name: frr-k8s-statuscleaner
  namespace: openshift-frr-k8s
  labels:
    app: frr-k8s
    component: frr-k8s-statuscleaner
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      component: frr-k8s-statuscleaner
  template:
    metadata:
      labels:
        component: frr-k8s-statuscleaner
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: privileged
    spec:
      containers:
      - command:
        - /statuscleaner
        args:
        - --disable-cert-rotation=true
        - --namespace=$(NAMESPACE)
        - --webhook-port=9123
        - --frrk8s-selector=component=frr-k8s
        - $(LOG_LEVEL)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: env-overrides
              key: frrk8s-loglevel
              optional: true
        image: {{.FRRK8sImage}}
        name: frr-k8s-statuscleaner
        ports:
        - containerPort: 9123
          name: webhook
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /healthz
            port: webhook
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: webhook
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
        operator: Exists
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: frr-k8s-webhook-server-cert
      serviceAccountName: frr-k8s-daemon
      priorityClassName: system-cluster-critical
      terminationGracePeriodSeconds: 10
      hostNetwork: true
