---
apiVersion: v1
kind: Service
metadata:
  name: frr-k8s-webhook-service
  namespace: openshift-frr-k8s
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: frr-k8s-webhook-server-cert
spec:
  ports:
  - port: 443
    targetPort: webhook
  selector:
    component: frr-k8s-statuscleaner
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: frr-k8s-validating-webhook-configuration-ocp
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: frr-k8s-webhook-service
      namespace: openshift-frr-k8s
      path: /validate-frrk8s-metallb-io-v1beta1-frrconfiguration
  failurePolicy: Fail
  name: frrconfigurationsvalidationwebhook.metallb.io
  rules:
  - apiGroups:
    - frrk8s.metallb.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frrconfigurations
  sideEffects: None
---
