apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  agent:
    ebpf:
      features:
        - DNSTracking
      sampling: 400
      metrics:
        server:
          tls:
            type: Auto
    type: eBPF
    processor:
      metrics:
        server:
          tls:
            type: Auto

  deploymentModel: Service
  loki:
    enable: false
  namespace: netobserv
